# Generated by Django 4.2.6 on 2023-10-16 03:13

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('mobile_number', models.CharField(max_length=200, unique=True, verbose_name='شماره موبایل')),
                ('mobile_activate_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد فعال سازی موبایل')),
                ('is_mobile_active', models.BooleanField(default=False, verbose_name='موبایل فعال / غیر فعال')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='ایمیل')),
                ('email_activate_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد فعال سازی موبایل')),
                ('is_email_active', models.BooleanField(default=False, verbose_name='موبایل فعال / غیر فعال')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=apps.account.models.upload_user_image, verbose_name='آواتار')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت نام')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مدیر')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیرکل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 't_users',
                'indexes': [models.Index(fields=['register_date'], name='t_users_registe_21dc19_idx'), models.Index(fields=['mobile_number'], name='t_users_mobile__a15db7_idx')],
            },
        ),
    ]
